# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read #  to fetch code (actions/checkout)

env:
  # run static analysis only with the latest Go version
  LATEST_GO_VERSION: "1.20"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.LATEST_GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.LATEST_GO_VERSION }}
          check-latest: true

      - name: golint
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status ./...
